#!/usr/bin/bash

NAME="cpu_2601"
VLANG="sv"
CXXLANG="cpp"

OPERATION="${1:-build}" # build | clean

## DIRECTORIES
CWD=$(pwd)
VERILATOR_ROOT="${2:-/usr/share/verilator}"

RTL_DIR="$CWD/rtl"
BUILD_DIR="$CWD/builddir"
VERILATOR_INCLUDE="$VERILATOR_ROOT/include"
VERILATOR_BIN="$VERILATOR_ROOT/bin"

## BINS
CXX="${3:-g++}"
MAKE="${4:-make}"
FIND="${5:-find}"
RM="${6:-rm}"
MKDIR="${7:-mkdir}"

VERILATOR="${VERILATOR_BIN}/verilator"

## FLAGS
VERILATOR_FLAGS="-I$RTL_DIR --Mdir $BUILD_DIR --cc"
CXX_FLAGS="-std=c++17 -I$VERILATOR_INCLUDE -I$BUILD_DIR -O3"

## FILES
TOP_OUT_ALL_NAME="libV${NAME}.a"
TOP_OUT_VERILATED_NAME="libverilated.a"

TOP="$RTL_DIR/$NAME.$VLANG"
TOP_OUT_ALL="$BUILD_DIR/$TOP_OUT_ALL_NAME"
TOP_OUT_VERILATED="$BUILD_DIR/$TOP_OUT_VERILATED_NAME"

SIM="$CWD/$NAME.$CXXLANG"
SIM_OUT="$BUILD_DIR/$NAME"

## HELPERS
function check_dir() {
    if [ ! -d "$1" ]; then
       return 1
    fi

    return 0
}

function mkdir_if_not() {
    if check_dir "$1"; then
        return
    fi

    $MKDIR "$1"
}

function rm_if() {
    if ! check_dir "$1"; then
        return
    fi

    $RM -r "$1"
}

function raise() {
    echo "ERROR: $1"
    exit 1
}

function log() {
    echo "LOG: $1"
}

function followup_log() {
    echo "--> $1"
}

function lnbreak() {
    echo ""
}

## BUILD

function prepare() {
   log "Checking Verilator root directory..."
    if ! check_dir "$VERILATOR_ROOT"; then
        raise "Verilator root directory '$VERILATOR_ROOT' does not exist"
    fi
    followup_log "Verilator root directory exists."
    lnbreak

    log "Creating build directory..."
    mkdir_if_not "$BUILD_DIR"
    followup_log "Build directory created."
    lnbreak
}

function configuration() {
    log "Configuration:"
    log "  CWD: $CWD"
    log "  VERILATOR_ROOT: $VERILATOR_ROOT"
    log "  RTL_DIR: $RTL_DIR"
    log "  BUILD_DIR: $BUILD_DIR"
    log "  CXX: $CXX"
    log "  FIND: $FIND"
    log "  VERILATOR: $VERILATOR"
    log "  TOP: $TOP"
    log "  SIM: $SIM"
    lnbreak
}

function verilate() {
    log "Starting Verilation..."
    $VERILATOR $VERILATOR_FLAGS $TOP
    followup_log "Verilation completed."
    lnbreak
}

function library() {
    log "Building simulation library..."
    make -C "$BUILD_DIR" -f V${NAME}.mk $TOP_OUT_ALL_NAME $TOP_OUT_VERILATED_NAME
    followup_log "Simulation library built."
    lnbreak
}

function simulation() {
    log "Building simulation executable..."
    $CXX $CXX_FLAGS -o "$SIM_OUT" "$SIM" "$TOP_OUT_ALL" "$TOP_OUT_VERILATED"
    followup_log "Simulation executable built."
    lnbreak
}

function build() {
    prepare
    verilate
    library
    simulation
}

function clean() {
    log "Cleaning build directory..."
    rm_if "$BUILD_DIR"
    followup_log "Build directory cleaned."
}

## OPERATION
configuration
if [ "$OPERATION" == "build" ]; then
    build
elif [ "$OPERATION" == "clean" ]; then
    clean
else
    raise "Unknown operation '$OPERATION'"
fi
